### ISSUE TITLE
Relationship/target unmodifiable in MembershipImpl

### ISSUE THREAD

**Issue by Rots** [Systems-Modeling/SysML-v2-Pilot-Implementation#356]
In the ecore definition the Relationship/target feature should be changeable (and is meant to be persisted):

https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/92f7022befe4f8a1940861ee7aa766ea8de26507/org.omg.sysml/model/SysML.ecore#L65-L74

(defaults to changeable=true, derived=false, transient=false)

But in MembershipImpl, the getTarget() is overridden from RelationsshipImpl and it returns a list which is unmodifiable:
https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/92f7022befe4f8a1940861ee7aa766ea8de26507/org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/MembershipImpl.java#L440-L453

Is this the intended behaviour? I'm trying to programmatically process the EMF object tree (using a third party library), but with this issue, the logic is not sound. Is the SysML v2 library not fully compatible with EMF semantics? Is there an overview of known discrepancies?

**Comment by seidewitz** [comment]
Note that the code for `getTarget` is generated, not handwritten. We use a slightly modified version of the importer from the Eclipse UML2 project (`org.eclipse.uml2.uml.ecore.importer.UMLImporter`) to generate code fromthe `SysML.uml` model file for the KerML and SysML abstract syntax metamodel. The `getTarget` code was generated as it would have been by the base `UMLImporter`, unaffected by our modifications.

In the normative MOF metamodel, the `Membership::memberElement` redefines `target` and restricts its multiplicity to 1. This is legal in UML/MOF, and it means that, in the scope of `Membership`, `memberElement` replaces `target` -- that is, the "target" of a `Membership` is always its single `memberElement`.

Of course, Ecore does not include the concept of property "redefinition". So, the UML2 project code generation does the best it can to fake this by overriding `getTarget` and returning a singleton list with just the value of `memberElement` in it. It should be considered invalid to "add" to this list, because the normative metamodel says it must have a multiplicity (size) of exactly 1 for a `Membership`. Programmatically, one should, instead, use `Membership::setMemberElement`, which effectively "replaces" the single target of the `Membership` with a new value.

Yes, this is technically not fully compatible with the usual EMF semantics. But it is an attempt to duplicate the more sophisticated UML/MOF semantics.
