### ISSUE TITLE
Function parameters should be owned via ParameterMemberships

### ISSUE THREAD

**Issue by YvesTLS** [Systems-Modeling/SysML-v2-Pilot-Implementation#438]
According to the KerML specification (§8.3.4.6.4 ParameterMembership): 

> The Feature that is identified as a parameter by this ParameterMembership, which is always owned by the
ParameterMembership.

However, at least in the KerML libraries it looks like it's the case for the return parameters only. E.g. the function "RationalFunction::rat"
has two inputs parameters defined using classical FeatureMemberships in the corresponding XMI (RationalFunctions.kermlx)

So, it looks like a XMI serialization bug.

**Comment by YvesTLS** [comment]
Note that the KerML specification is ambiguous here. Indeed §8.3.4.6.2 Behavior says:

>The parameters of this Behavior, which are all its directedFeatures, whose values are passed into and/or out of a performance of the Behavior.

Which is not exactly the same as the part referenced in my previous comment => a clarification is required

**Comment by seidewitz** [comment]
The wording in 8.3.4.6.4 is not intended to mean that all parameters are owned via ParameterMemberships, but, rather, that the member element of a ParameterMembership is always owned by that relationship. The wording is left over from before the abstract syntax had a separate OwningMembership relationship, at which time Membership relationships in general could be owning or not -- but ParameterMemberships in particular were constrained to be owning. However, ParameterMembership is now a kind of OwningMembership, so the comment on ownership for the ownedMemberParameter property is probably unnecessary, and obviously can be confusing (plus the ownership is pretty obvious just from the name of property!).

**Comment by YvesTLS** [comment]
Ed,
So it could be an issue for Track#4. Indeed, I don't get why on the one hand we have this ParameterMembership relation and on the other end some parameters that may be owned using regular FeatureMemberships. Is there any rational for this?

**Comment by seidewitz** [comment]
There are certain cases where features are parsed for various notational constructs in concrete syntax without any explicit direction being given, but they are still supposed to be parameters. For example, an invocation expression such as `F(1,2)` is parsed (in KerML notation) like
```
expr : F {
    in x redefines F::x = 1;
    in y redefines F::y = 2;
}
```
As shown, the parameters `x` and `y` are supposed to have the direction `in`, but this is not explicit in the notation `F(1,2)`. Parsing the arguments of the invocation as Features owned by ParameterMembership is simply a convenience to indicate that they are supposed to be a parameters with a direction. Rather than having to state this constraint in each place that it happens (there are a couple additional cases each in the KerML and SysML syntax), it is simpler to just put the constraint on ParameterMembership that its owned Feature must have a non-null direction (and the implementation then defaults the direction to `in`, unless its a ReturnParameterMembership, in which case the default is `out`). 

If a parameter has an explicit direction given in its concrete syntax declaration, or if the abstract syntax tree is created directly and a the direction is set programmatically, then there is no need to use a ParameterMembership.
