### ISSUE TITLE
PlantUML visualization skin not found

### ISSUE THREAD

**Issue by podhrmic** [Systems-Modeling/SysML-v2-Pilot-Implementation#476]
Hi, I am experimenting with the PlantUML visualization, and I am having problems rendering SysMLv2 diagrams without the Eclipse plugin.

Specifically, let's use [the following vehicle definitions example](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/master/sysml/src/examples/Vehicle%20Example/VehicleDefinitions.sysml#L18):
```
	part def Axle {
		port leftMountingPoint: AxleMountIF;
		port rightMountingPoint: AxleMountIF;
	}
```

In the Eclipse, this gets rendered as expected:
![Screenshot from 2023-03-02 17-09-58](https://user-images.githubusercontent.com/2790461/222606320-7fea5411-0d65-43a7-b786-3fd3436a0bab.png)

The SysML plugin generates the following code ([this function](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/master/org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java#L459)):
```
@startuml
skin sysmlbw
skinparam monochrome true
skinparam wrapWidth 300
hide circle

comp def "Axle" as E1  <<(T,blue) part  def>> [[psysml:6fb73ea9-9850-4b45-ba3c-48a845075c3d ]] {
}
comp usage "leftMountingPoint: AxleMountIF " as E2  <<(T,blue) port>> [[psysml:468ce2d7-14a1-4b1e-aca3-17e58044f0bf ]] {
}
comp usage "rightMountingPoint: AxleMountIF " as E3  <<(T,blue) port>> [[psysml:95d05009-6c72-415f-b3e6-f7d183c373f0 ]] {
}
E1 o-- E2 [[psysml:b2e8b17e-0e14-4633-b239-2a74eb2d6f74 ]] 
E1 o-- E3 [[psysml:538c18e7-e9da-4100-98cc-dcb91806c687 ]] 
@enduml
```

However, if I save this and try to pass the generated code to a standalone plantuml library (the same version as the plugin uses), I get two errors:

```
Cannot find skin sysmlbw
```

And when I remove `skin sysmlbw` I get a syntax error.

Where is `sysmlbw` defined? And what else needs to be defined to avoid the syntax error?

**Comment by seidewitz** [comment]
This looks like a configuration problem. It is best to (initially at least) install the Jupyter kernel from the release repository:

https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/install/jupyter

Once this is working, intermediate development revisions of the kernel can then be built directly from the SysML v2 Pilot Implementation repository, if desired.

If you continue to have problems, it is best to post a question to the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), rather than in a GitHub issue. (I noted that you requested access to the group, which has been granted.)
