### ISSUE TITLE
EMF ecore of SysML Doesn't Depend on KerML

### ISSUE THREAD

**Issue by danyeaw** [Systems-Modeling/SysML-v2-Pilot-Implementation#496]
Hi, I was expecting that the [SysML ecore](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/master/org.omg.sysml/model/SysML.ecore) would depend on the [KerML ecore](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/master/org.omg.sysml/model/kerml.ecore). Instead, it looks like it is redefining everything that has already been defined in KerML.

**Comment by seidewitz** [comment]
Our EMF implementation currently requires a combined SysML/KerML metamodel in order to properly represent references to KerML model elements within SysML models. For technical reasons related to our use of Xtext, it has been difficult to divide this into separate ePackages, so the SysML.ecore file has a combined SysML/KerML Ecore metamodel in a single ePackage. We may revisit this in the future to try to find a better resolution, particularly as we wish to better separate the KerML and SysML implementations in general.
