### ISSUE TITLE
Installing extensions with jupyter labextension install is deprecated 

### ISSUE THREAD

**Issue by GorgiAstro** [Systems-Modeling/SysML-v2-Pilot-Implementation#523]
Installing jupyter lab extensions should now be done with pip or conda:

`~$ jupyter labextension install "@systems-modeling/jupyterlab-sysml"`

> (Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.
> 
> Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages

**Comment by seidewitz** [comment]
This is true for later versions of Jupyter. Currently we are only supporting Jupyter 2.x.

**Comment by kiniry** [comment]
Hi @seidewitz.  Only after attempting to install the Jupyter-based Pilot Implementation on my other work machine (an ARM Mac, rather than my x86 Mac), having the installation say it succeeded, then running `jupyter lab` and not seeing support for SysML notebooks, then digging around a lot, did I find this and sister issues mentioning the Jupyter 2.x dependency.  I recommend that dependency is documented in the release.  A find/grep of the entire release reveals no mention of this fact.  Perhaps I missed it.

**Comment by seidewitz** [comment]
The issue with AARM Mac was really with the versions of Jupyter Lab and Node.js. We updated to Jupyter Lab version 3.x and a later version of Node.js months ago to resolve this. It should be possible to install on Mac without problem (I can).
