### ISSUE TITLE
How to set Definition in a Usage instance?

### ISSUE THREAD

**Issue by Orangewithsugar** [Systems-Modeling/SysML-v2-Pilot-Implementation#599]
Hi SysML Team~
I got the problem of how to set the Definition in a Usage instance, if  I set it directly, it seems nothing happens, but if I create a featureTyping and set the specific and general, and set the featureTyping into a usage, the usage still did not load the corresponding definition.

Best Regards.

**Comment by seidewitz** [comment]
There is one list of `ownedRelationship` for an element, and any new relationship must be added to this list. Other properties, like `ownedSpecialization`, `ownedTyping`, etc. are all derived, and adding an element to those values will have no effect. So, once you have created your `FeatureTyping` relationship, you need to call `getOwnedRelationship` on the `specific` element and add the `FeatureTyping` relationship to that list.

If you would like to discuss this further, please join the Google Group at https://groups.google.com/g/sysml-v2-release and post your question there, rather than as a GitHub issue.

**Comment by Orangewithsugar** [comment]
Got it ,Thank you~ 
I will discuss on google group later on.
